library(TwoSampleMR)
library(data.table)
library(dplyr)
library(tidyr)
#Pain in throat and chest
bmi_exp_dat <- extract_instruments(outcomes = 'ebi-a-GCST90000514')
outcome_dat <- extract_outcome_data(snps = bmi_exp_dat$SNP, outcomes = 'ukb-a-581')
dat<-harmonise_data(exposure_dat = bmi_exp_dat,outcome_dat = outcome_dat)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))
library(MRPRESSO)
mr_presso(BetaOutcome ="beta.outcome", BetaExposure = "beta.exposure", SdOutcome ="se.outcome", SdExposure = "se.exposure", 
          OUTLIERtest = TRUE,DISTORTIONtest = TRUE, data = dat, NbDistribution = 10000,  
          SignifThreshold = 0.05)
write.csv(dat,"GERD_MRPRESSO.csv")
#Remove Outliers,Phenoscanner
dat<-fread("GERD_MRPRESSO_Remove_Outliers.csv",header = TRUE)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))
#Cough on most days
bmi_exp_dat <- extract_instruments(outcomes = 'ebi-a-GCST90000514')
outcome_dat <- extract_outcome_data(snps = bmi_exp_dat$SNP, outcomes = 'ukb-a-258')
dat<-harmonise_data(exposure_dat = bmi_exp_dat,outcome_dat = outcome_dat)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))
library(MRPRESSO)
mr_presso(BetaOutcome ="beta.outcome", BetaExposure = "beta.exposure", SdOutcome ="se.outcome", SdExposure = "se.exposure", 
          OUTLIERtest = TRUE,DISTORTIONtest = TRUE, data = dat, NbDistribution = 10000,  
          SignifThreshold = 0.05)
write.csv(dat,"GERD_MRPRESSO.csv")
#Remove Outliers,Phenoscanner
dat<-fread("GERD_MRPRESSO_Remove_Outliers.csv",header = TRUE)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))
#Asthma
bmi_exp_dat <- extract_instruments(outcomes = 'ebi-a-GCST90000514')
outcome_dat<-read_outcome_data(filename="finngen_Asthma.txt", snps = bmi_exp_dat$SNP, sep = "\t",snp_col = "rsids",beta_col = "beta",se_col = "sebeta",effect_allele_col = "alt",other_allele_col = "ref",pval_col = "pval")
dat<-harmonise_data(exposure_dat = bmi_exp_dat,outcome_dat = outcome_dat)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))
library(MRPRESSO)
mr_presso(BetaOutcome ="beta.outcome", BetaExposure = "beta.exposure", SdOutcome ="se.outcome", SdExposure = "se.exposure", 
          OUTLIERtest = TRUE,DISTORTIONtest = TRUE, data = dat, NbDistribution = 10000,  
          SignifThreshold = 0.05)
write.csv(dat,"GERD_MRPRESSO.csv")
#Remove Outliers,Phenoscanner
dat<-fread("GERD_MRPRESSO_Remove_Outliers.csv",header = TRUE)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))
#Bronchitis
bmi_exp_dat <- extract_instruments(outcomes = 'ebi-a-GCST90000514')
outcome_dat<-read_outcome_data(filename="finngen_Bronchitis.txt", snps = bmi_exp_dat$SNP, sep = "\t",snp_col = "rsids",beta_col = "beta",se_col = "sebeta",effect_allele_col = "alt",other_allele_col = "ref",pval_col = "pval")
dat<-harmonise_data(exposure_dat = bmi_exp_dat,outcome_dat = outcome_dat)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))

#Chronic rhinitsi, nasopharyngitis and pharyngitis
bmi_exp_dat <- extract_instruments(outcomes = 'ebi-a-GCST90000514')
outcome_dat<-read_outcome_data(filename="finngen_Chronic_rhinitsi_nasopharyngitis_and_pharyngitis.txt", snps = bmi_exp_dat$SNP, sep = "\t",snp_col = "rsids",beta_col = "beta",se_col = "sebeta",effect_allele_col = "alt",other_allele_col = "ref",pval_col = "pval")
dat<-harmonise_data(exposure_dat = bmi_exp_dat,outcome_dat = outcome_dat)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))

#Gingivitis and periodontal diseases
bmi_exp_dat <- extract_instruments(outcomes = 'ebi-a-GCST90000514')
outcome_dat<-read_outcome_data(filename="finngen_Gingivitis_and_periodontal_diseases.txt", snps = bmi_exp_dat$SNP, sep = "\t",snp_col = "rsids",beta_col = "beta",se_col = "sebeta",effect_allele_col = "alt",other_allele_col = "ref",pval_col = "pval")
dat<-harmonise_data(exposure_dat = bmi_exp_dat,outcome_dat = outcome_dat)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))
library(MRPRESSO)
mr_presso(BetaOutcome ="beta.outcome", BetaExposure = "beta.exposure", SdOutcome ="se.outcome", SdExposure = "se.exposure", 
          OUTLIERtest = TRUE,DISTORTIONtest = TRUE, data = dat, NbDistribution = 10000,  
          SignifThreshold = 0.05)
write.csv(dat,"GERD_MRPRESSO.csv")
#Remove Outliers,Phenoscanner
dat<-fread("GERD_MRPRESSO_Remove_Outliers.csv",header = TRUE)
OR<-generate_odds_ratios(mr_res = mr(dat))
mr_scatter_plot(mr_results = mr(dat,method_list = c("mr_ivw","mr_egger_regression","mr_weighted_median")),dat)
mr_heterogeneity<-mr_heterogeneity(dat)
mr_funnel_plot(singlesnp_results = mr_singlesnp(dat))
mr_pleiotropy_test<-mr_pleiotropy_test(dat)
mr_leaveoneout_plot(leaveoneout_results = mr_leaveoneout(dat))